1. What does Pandas stand for?
- References both “Panel Data” and “Python Data Analysis”
2. What are the 2 collections used in Pandas?
- series
- dataframes
3. Name 4 things Pandas can do for us.
- data cleansing
- data normalization 
- data visiualization 
- data inspection
4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
- df.sort_values(" ")
5. What is a CSV?
- (comma separated files) CSV files contains plain text and is a well know format that can be read by everyone including Pandas.
6. When cleaning data what values do we not like in our data?
- Nulls

In [16]:
# Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`
import numpy as np

x = np.array([1,2,3,4,5,6,7,8,9])
print(x)

[1 2 3 4 5 6 7 8 9]


In [17]:
newShape = x.reshape(3, -1)
print (newShape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
# Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20

linear = np.linspace(0,20, num=6)
print(linear)

[ 0.  4.  8. 12. 16. 20.]


In [19]:
# Make a Deep Copy of the above array
import copy

copylinear = copy.deepcopy(linear)
print(copylinear)

[ 0.  4.  8. 12. 16. 20.]


In [20]:
# Concatenate these 3 arrays into a new array named 'newArray'...

first = ([[25, 16]])
second = ([[11, 2], [13, 4]])
third = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((first, second, third),axis=0)
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [21]:
# Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [23]:
#Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. 
#Print the 4 variables.

a, b, c, d, e, f = sortedArray
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

[16 25]
[ 2 11]
[ 4 13]
[ 7 81]
[5 6]
[11 12]


In [25]:
#Combined and sort the following arrays into one called 'comboArray'

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three))
comboArray = np.sort(comboArray)
print(comboArray)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [38]:
#sec1
print(comboArray[1])
#sec2
print(comboArray[2:])
#sec3
print(comboArray[3:14])
#sec4
print(comboArray[-6:])
#sec5
print(comboArray[:-9])
#sec6
print(comboArray[20::2])
#sec7
print(comboArray[::-5])

1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16]
[24 26]
[27 22 15 10  3]


In [49]:
import numpy as np
import pandas as pd

In [64]:
Ingredients = pd.Series(["Flour","Milk","Eggs","Spam"], name="ingredients")
Quantity = pd.Series([4,1,2,1], name="Quantity")
Unit = pd.Series(["cups","cup","large","can"],name="unit")
dinner = pd.concat([Ingredients, Quantity, Unit], axis=1)
dinner

ingredients  Quantity   unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

In [69]:
studentData= pd.DataFrame({'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        })
studentData

Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

In [81]:
studentData ['deserts'] = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData

Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa

In [90]:
studentData.sort_values(by = ["Name","address"], inplace=True)
studentData

Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge

In [93]:
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')
df=pd.read_csv('cows_and_goats.csv')
df

Unnamed: 0  Cows  Goats
0     Year 1    12     22
1     Year 2    20     19

In [106]:
import pandas as pd

vegetables = pd.DataFrame({"Potato": ['fries','chips'], 
                                 "Broccoli": ['soup', 'salad']})
vegetables
vegetables.to_csv("vegetables.csv")

In [109]:
edit = pd.read_csv("vegetables.csv")
edit = vegetables.replace(to_replace = ["salad"], value = ["stew"])
edit

edit.to_csv("vegetables_edit.csv")
